version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
  test:
    docker:
      - image: cimg/python:3.10.2
    working_directory: /tmp
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests and save it as artifact
          command: |
            . venv/bin/activate
            mkdir test-reports
            pytest > test-reports
      - store_artifacts:
          path: test-reports/
          destination: python_app
      - store_test_results:
          path: test-reports/

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
              branches:
                only: main
      - test:
          requires:
            - build
