version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Run tests
          command: pytest

workflows:
  build_and_test:
    jobs:
      - build
      - test