# Generated by Django 3.0 on 2022-02-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0002_auto_20220217_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='LettingReview',
            fields=[
            ],
            options={
                'verbose_name': 'Letting',
                'verbose_name_plural': 'Lettings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lettings.letting',),
        ),
    ]
