# Generated by Django 3.0 on 2022-02-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0003_lettingreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileReview',
            fields=[
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('profiles.profile',),
        ),
    ]
